name: Build EXE and Upload to Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-windows-exe:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install textual

      - name: Build EXE
        run: |
          pyinstaller blackjack.spec

      - name: Upload EXE to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/blackjack/blackjack.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
